[project]
name = "roblox-charts-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "selenium>=4.39.0",
    "webdriver-manager>=4.0.2",
]
